#!/usr/bin/env python3
"""Pull the character data, portraits and animated loops this page needs from the shared asset
bundle (~/projects/game-assets, `./assets.py all` there):
  chars.js         const CHARS = [{i, n, e, w, s}]   (bundle order: newest release first)
  img/<id>.webp    square art, 192 px              (detail modal)
  img/roster/*.webp tall art, 200 px wide          (roster, team slots, bench; the Rovers share rover.webp)
  img/live/<id>.webm + live.js                     animated roster portraits (the bundle's 176x220 "small" loop)
The shared Rover card keeps its static art: one card for four forms, gender not chosen yet.
Team data (teams.js, sequences.js, weapons.js) still comes from this repo's own update-*.py.
  python3 tools/sync-assets.py"""
import json, os, shutil, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.environ.get("GAME_ASSETS_DIST", os.path.expanduser("~/projects/game-assets/dist"))
SIZE, ROSTER_W = 192, 200


def load(rel):
    return json.load(open(os.path.join(SRC, rel), encoding="utf-8"))


def fresh(src, dst):
    return os.path.exists(dst) and os.path.getmtime(dst) >= os.path.getmtime(src)


def resized(rel_src, rel_dst, box, quality, keep):
    from PIL import Image
    src, dst = os.path.join(SRC, rel_src), os.path.join(HERE, rel_dst)
    keep.add(dst)
    if fresh(src, dst):
        return
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    im = Image.open(src)
    im.thumbnail(box, Image.LANCZOS)
    im.save(dst, "WEBP", quality=quality)


def copied(rel_src, rel_dst, keep):
    src, dst = os.path.join(SRC, rel_src), os.path.join(HERE, rel_dst)
    keep.add(dst)
    if not fresh(src, dst):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)


def main():
    chars, portraits = load("wuwa/characters.json"), load("wuwa/portraits.json")
    keep, live = set(), {}
    for c in chars:
        if c["img"].get("icon"):
            resized(c["img"]["icon"], f"img/{c['id']}.webp", (SIZE, SIZE), 80, keep)
        if c["img"].get("card"):
            resized(c["img"]["card"], f"img/roster/{os.path.basename(c['img']['card'])}", (ROSTER_W, ROSTER_W * 2), 82, keep)
        loop = portraits.get(c.get("portrait") or "", {}).get("small")
        if loop and not c.get("group"):
            copied(loop, f"img/live/{c['id']}.webm", keep)
            live[c["id"]] = f"img/live/{c['id']}.webm"
    data = [{"i": c["id"], "n": c["name"], "e": c["element"], "w": c["weapon"], "s": c["rarity"]} for c in chars]
    with open(os.path.join(HERE, "chars.js"), "w", encoding="utf-8") as f:
        f.write("const CHARS=" + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
    with open(os.path.join(HERE, "live.js"), "w") as f:
        f.write("// Generated by tools/sync-assets.py: animated roster portraits (WebM VP9 + alpha)\n")
        f.write("const LIVE = " + json.dumps(live, separators=(",", ":")) + ";\n")
    stale = [os.path.join(d, f) for d in (os.path.join(HERE, "img"), os.path.join(HERE, "img", "roster"), os.path.join(HERE, "img", "live"))
             for f in os.listdir(d) if os.path.isfile(os.path.join(d, f)) and os.path.join(d, f) not in keep]
    for p in stale:
        os.remove(p)
    size = sum(os.path.getsize(os.path.join(HERE, p)) for p in live.values())
    static = [c["name"] for c in chars if c["id"] not in live]
    print(f"chars.js: {len(data)} characters; {len(live)} animated ({size / 1e6:.1f} MB); static only: {', '.join(static)}; "
          f"removed {len(stale)} stale files")


if __name__ == "__main__":
    sys.exit(main())
