#!/usr/bin/env python3
"""Regenerate weapons.js from arabwuwa's per-character weapon comparison.

Every character page carries a "Weapon comparison / Relative damage" section
listing weapons at various refinements with their damage relative to the
character's signature at R1 (= 100%). We read the R1 rows, treat the 100% entry
as the signature, and record the best standard-banner weapon of that type.

    python3 tools/update-weapons.py
"""
import html
import json
import pathlib
import re
import sys
import urllib.request

ORIGIN = "https://arabwuwa.com"
WEAPON_DATA = ORIGIN + "/data/weapons.json"
ROOT = pathlib.Path(__file__).resolve().parent.parent
UA = {"User-Agent": "Mozilla/5.0 (resonator-rotation updater)"}

# The standard-banner 5-stars: what you fall back on without the signature.
STANDARD = {
    "laser-shearer", "radiance-cleaver", "phasic-homogenizer", "pulsation-bracer", "boson-astrolabe",
    "emerald-of-genesis", "lustrous-razor", "static-mist", "abyss-surges", "cosmic-ripples",
}

CARD = re.compile(
    r'<article class="character-page-weapon-section-item awcd-weapon-card" data-refine-rank="(\d)">(.*?)</article>',
    re.S)
SLUG = re.compile(r'/images/weapons/150px/([a-z0-9-]+)\.webp')
PCT = re.compile(r'character-page-weapon-section-damage"><strong><bdi[^>]*>([\d.]+)%')
NAME = re.compile(r'weapon-section-name"[^>]*>([^<]+)')


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode("utf-8", "replace")


def cards_for(page):
    out = []
    for rank, body in CARD.findall(page):
        slug, pct, name = SLUG.search(body), PCT.search(body), NAME.search(body)
        if not (slug and pct):
            continue
        out.append({
            "rank": int(rank), "id": slug.group(1), "pct": float(pct.group(1)),
            "name": html.unescape(name.group(1) if name else slug.group(1)).strip(),
        })
    return out


def main():
    rarity = {w["id"]: w.get("rarity") for w in json.loads(fetch(WEAPON_DATA))}
    ids = re.findall(r'"i":"([^"]+)"', (ROOT / "chars.js").read_text(encoding="utf-8"))
    out, skipped = {}, []
    for cid in ids:
        try:
            cards = cards_for(fetch(f"{ORIGIN}/characters/{cid}/"))
        except Exception as exc:
            print(f"  ! {cid}: {exc}", file=sys.stderr)
            continue
        if not cards:
            skipped.append(cid)
            continue

        # The signature is the R1 weapon the page normalises to.
        base = next((c for c in cards if c["rank"] == 1 and abs(c["pct"] - 100.0) < 0.01), None)
        if not base:
            skipped.append(cid)
            continue

        # Best standard-banner option at the highest refinement published: a
        # standard 5-star is the one weapon you realistically get to R5, so R5
        # is the honest assumption, with R3/R1 used only when that is all there is.
        # Where the page compares no standard weapon at all, the best 4-star in
        # the list stands in — that is the other thing everyone actually owns.
        kind = "standard"
        pool = [c for c in cards if c["id"] in STANDARD]
        if not pool:
            kind = "4star"
            pool = [c for c in cards if rarity.get(c["id"]) == 4 and c["id"] != base["id"]]
        if pool:
            pool.sort(key=lambda c: (-c["rank"], -c["pct"]))
            std = pool[0]
        else:
            # Nothing you are guaranteed to own is charted, so fall back to the
            # weakest alternative published: an understatement beats a fantasy.
            kind = "worst"
            pool = [c for c in cards if c["id"] != base["id"]]
            if not pool:
                skipped.append(cid)
                continue
            pool.sort(key=lambda c: (c["pct"], -c["rank"]))
            std = pool[0]

        out[cid] = {
            "s": base["name"], "sid": base["id"],
            "b": std["name"], "bid": std["id"],
            "f": round(std["pct"] / 100.0, 4),
            "r": std["rank"],
            "k": kind,
        }
        tag = {"standard": "", "4star": "  [4-star stand-in]", "worst": "  [weakest listed]"}[kind]
        print(f"  {cid:16} {base['name']:24} -> {std['name']} R{std['rank']}  {std['pct']:.2f}%{tag}")

    (ROOT / "weapons.js").write_text(
        "// Generated by tools/update-weapons.py from the per-character\n"
        "// \"Weapon comparison / Relative damage\" section on arabwuwa.com.\n"
        "// s/sid: signature weapon at R1, the 100% baseline the DPS figures assume.\n"
        "// b/bid/r: the fallback weapon, at the highest refinement published.\n"
        "// k: \"standard\" (standard-banner 5-star), \"4star\" (best 4-star when no standard\n"
        "//    weapon is charted) or \"worst\" (weakest alternative, when neither exists).\n"
        "// f: its share of the signature's damage.\n"
        "const WEAPONS=" + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    if out:
        fs = sorted(v["f"] for v in out.values())
        print(f"\nwrote weapons.js: {len(out)} characters, factor {fs[0]:.3f}-{fs[-1]:.3f}, median {fs[len(fs)//2]:.3f}")
    print(f"no comparison published for {len(skipped)}: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
