#!/usr/bin/env python3
"""Regenerate teams.js from the arabwuwa.com Team DPS projection.

The /team-dps/ page references a revision-hashed dataset directory; the
revision changes whenever the projection is rebuilt, so it is discovered
from the page rather than hard-coded.

    python3 tools/update-teams.py
"""
import json
import pathlib
import re
import sys
import urllib.request

PAGE = "https://arabwuwa.com/team-dps/"
ORIGIN = "https://arabwuwa.com"
ROOT = pathlib.Path(__file__).resolve().parent.parent
UA = {"User-Agent": "Mozilla/5.0 (resonator-rotation updater)"}


def get(url: str) -> bytes:
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30) as r:
        return r.read()


def main() -> int:
    page = get(PAGE).decode("utf-8", "replace")
    m = re.search(r"/data/team-dps-generated/([0-9a-f]{16,})/listing\.en\.json", page)
    if not m:
        print("could not find the listing URL on " + PAGE, file=sys.stderr)
        return 1
    revision = m.group(1)
    listing = json.loads(get(f"{ORIGIN}/data/team-dps-generated/{revision}/listing.en.json"))

    idx = {k: i for i, k in enumerate(listing["tupleFields"]["team"])}
    known = set(re.findall(r'"i":"([^"]+)"', (ROOT / "chars.js").read_text(encoding="utf-8")))

    teams, skipped = [], 0
    for t in listing["teams"]:
        members = [c[0] for c in t[idx["characters"]]]
        if not members or any(m not in known for m in members):
            skipped += 1          # a team built around a character we have no portrait for
            continue
        teams.append({
            "r": t[idx["overallRank"]],
            "n": t[idx["name"]],
            "d": round(t[idx["threeRotationsDps"]] or 0),
            "b": t[idx["difficultyBucket"]] or "",
            "c": members,
        })
    teams.sort(key=lambda x: (x["r"] or 9999, -x["d"]))

    (ROOT / "teams.js").write_text(
        "// Generated by tools/update-teams.py from the arabwuwa.com Team DPS projection.\n"
        f"// revision {revision}\n"
        "const TEAMS=" + json.dumps(teams, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    covered = {m for t in teams for m in t["c"]}
    print(f"wrote teams.js: {len(teams)} teams, {len(covered)} characters covered, {skipped} skipped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
