#!/usr/bin/env python3
"""Animated roster portraits for the team builder.

Takes the baked upper-body loops (WebM VP9 + alpha) from the pull tracker
(~/projects/gacha-tracker/img/wuwa/live/<Portraits_X>.bust.webm, made from the game's own
Spine formation portraits) and re-encodes them small for this page:
  img/live/<id>.webm   176x220, one seamless idle cycle, 30 fps
Writes live.js: const LIVE = {id: "img/live/<id>.webm"}. Characters without a loop (and the
shared Rover card) keep their static roster art.
  python3 tools/update-live.py [--force]
"""
import json, os, re, subprocess, sys

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACKER = os.path.expanduser("~/projects/gacha-tracker")
FORCE = "--force" in sys.argv


def js_obj(path, marker):
    return json.loads(re.search(marker + r"\s*=\s*(\{.*?\}|\[.*?\]);", open(path).read(), re.S).group(1))


def main():
    chars = js_obj(os.path.join(HERE, "chars.js"), "CHARS")
    spine = js_obj(os.path.join(TRACKER, "data", "wuwa-spine.js"), r"\.wuwa")
    live = js_obj(os.path.join(TRACKER, "data", "wuwa-live.js"), r"\.wuwa")
    alias = {"xuanling": "yangyang: xuanling"}           # team-builder name -> in-game pull name
    out_dir = os.path.join(HERE, "img", "live")
    os.makedirs(out_dir, exist_ok=True)
    result, missing = {}, []
    for c in chars:
        if c["i"].startswith("rover"):                     # one shared Rover card, gender unknown
            continue
        name = c["n"].lower()
        sp = spine.get(name) or spine.get(alias.get(name, ""))
        src = sp and live.get(sp, {}).get("bust")
        if not src:
            missing.append(c["n"]); continue
        dst = os.path.join(out_dir, c["i"] + ".webm")
        if FORCE or not os.path.exists(dst):
            subprocess.run(["nice", "-n", "15", "ffmpeg", "-v", "error", "-y", "-c:v", "libvpx-vp9", "-i", os.path.join(TRACKER, src),
                            "-vf", "scale=176:220:flags=lanczos", "-c:v", "libvpx-vp9", "-pix_fmt", "yuva420p",
                            "-crf", "40", "-b:v", "0", "-row-mt", "1", "-an", dst], check=True)
        result[c["i"]] = f"img/live/{c['i']}.webm"
    with open(os.path.join(HERE, "live.js"), "w") as f:
        f.write("// Generated by tools/update-live.py: animated roster portraits (WebM VP9 + alpha)\n")
        f.write("const LIVE = " + json.dumps(result, separators=(",", ":")) + ";\n")
    size = sum(os.path.getsize(os.path.join(HERE, p)) for p in result.values())
    print(f"{len(result)} animated portraits, {size / 1e6:.1f} MB; static only: {', '.join(missing) or '-'}")


if __name__ == "__main__":
    main()
