#!/usr/bin/env python3
"""Regenerate sequences.js from arabwuwa's "Sequence damage comparison".

Each character page carries the chart as a single element:

    <section class="awcd-sequence-damage" data-values="100,108,132,170,181,195,394" ...>

where the values are damage relative to S0. Pages that publish one chart per
rotation are read from the first chart.

The Team DPS projection does not calculate everyone at S0 - the free and
standard characters are assumed at S6 - so the baseline sequence per character
is taken from the projection itself and stored alongside.

    python3 tools/update-sequences.py
"""
import collections
import json
import pathlib
import re
import sys
import urllib.request

ORIGIN = "https://arabwuwa.com"
ROOT = pathlib.Path(__file__).resolve().parent.parent
UA = {"User-Agent": "Mozilla/5.0 (resonator-rotation updater)"}
CHART = re.compile(r'class="[^"]*awcd-sequence-damage[^"]*"[^>]*data-values="([0-9.,\s]+)"')


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read().decode("utf-8", "replace")


def main():
    ids = re.findall(r'"i":"([^"]+)"', (ROOT / "chars.js").read_text(encoding="utf-8"))

    # Baseline sequence per character, straight from the projection's builds.
    page = fetch(ORIGIN + "/team-dps/")
    m = re.search(r"/data/team-dps-generated/([0-9a-f]{16,})/listing\.en\.json", page)
    if not m:
        print("could not find the Team DPS listing", file=sys.stderr)
        return 1
    listing = json.loads(fetch(f"{ORIGIN}/data/team-dps-generated/{m.group(1)}/listing.en.json"))
    ti = {k: i for i, k in enumerate(listing["tupleFields"]["team"])}
    bi = {k: i for i, k in enumerate(listing["tupleFields"]["firstRotationBuild"])}
    seen = collections.defaultdict(collections.Counter)
    for team in listing["teams"]:
        for build in team[ti["firstRotationBuilds"]]:
            seen[build[bi["characterId"]]][build[bi["sequence"]]] += 1
    baseline = {c: v.most_common(1)[0][0] for c, v in seen.items()}

    out, skipped = {}, []
    for cid in ids:
        try:
            found = CHART.search(fetch(f"{ORIGIN}/characters/{cid}/"))
        except Exception as exc:
            print(f"  ! {cid}: {exc}", file=sys.stderr)
            continue
        if not found:
            skipped.append(cid)
            continue
        values = [float(x) for x in found.group(1).split(",") if x.strip()]
        if len(values) != 7 or values[0] <= 0:
            skipped.append(cid)
            continue
        base = baseline.get(cid, 0)
        out[cid] = {"v": [round(v, 2) for v in values], "s0": base}
        note = f"  (projection assumes S{base})" if base else ""
        print(f"  {cid:16} {'/'.join(str(int(v)) for v in values)}{note}")

    (ROOT / "sequences.js").write_text(
        "// Generated by tools/update-sequences.py from the\n"
        "// \"Sequence damage comparison\" chart on each arabwuwa character page.\n"
        "// v: damage at S0..S6, relative to S0 = 100.\n"
        "// s0: the sequence the Team DPS projection calculates that character at.\n"
        "const SEQUENCES=" + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8",
    )
    print(f"\nwrote sequences.js: {len(out)} characters")
    print(f"no chart published for {len(skipped)}: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
